export type Society = 'Bacchus' | 'Bellona' | 'Pheme';
export type Status = 'a' | 'b' | 'g' | 'd' | 'e' | '?';
export type Year = 0 | 1 | 2 | 3 | 4 | 99;
export type PersonType = 'Discipli' | 'Questi';

export type Person = {
  id: string,
  rank: number,
  family: string,
  name: string,
  society: Society,
  status: Status,
  current: boolean,
  year: Year,
  type: PersonType,
  score: number,
};

export const statusCollection: { [key in Status]: string } = {
  a: 'α',
  b: 'β',
  g: 'γ',
  d: 'δ',
  e: 'ε',
  '?': '?',
};

const years: Year[] = [1, 2, 3, 4];
const societies: Society[] = [
  'Bacchus',
  'Bellona',
  'Pheme',
];
const familyStatus: { [key: string]: 'a' | 'b' | undefined } = {
  Adrasteia: 'b',
  Aesculapius: 'a',
  Ambrosia: 'b',
  Aphrodite: 'a',
  Apollon: 'a',
  Arachne: 'b',
  Ares: 'a',
  Artemis: 'a',
  Athena: 'a',
  Atlas: 'a',
  Calypso: 'a',
  Calliope: 'b',
  Dekton: 'b',
  Demeter: 'a',
  Dido: 'b',
  Dirke: 'b',
  'Dius Fidus': 'a',
  Europa: 'b',
  Fortuna: 'a',
  Hefaistos: 'a',
  Helios: 'a',
  Hestia: 'a',
  Hera: 'a',
  Janus: 'a',
  Juno: 'a',
  Jupiter: 'a',
  Juventa: 'a',
  Landon: 'b',
  Luna: 'a',
  Lynx: 'b',
  Manticora: 'b',
  'Medusa ': 'b',
  Mercuri: 'a',
  Minerva: 'a',
  Mithras: 'a',
  Mota: 'b',
  Nerio: 'a',
  Nike: 'a',
  Nyx: 'a',
  Oceanus: 'a',
  Orion: 'b',
  Pan: 'a',
  Pandora: 'b',
  Persefone: 'a',
  Poseidon: 'a',
  Prometheus: 'b',
  Proteus: 'a',
  Sfinx: 'b',
  Silvanus: 'a',
  Satyr: 'b',
  Soteira: 'a',
  Talos: 'b',
  Thanatos: 'a',
  Vesta: 'a',
  Vulcanus: 'a',
};

export const discipli: Person[] = [
  'Cleopensia Nyx',
  'Themisine Janus',
  'Hercules M. Deimos',
  'Nezzie Landon',
  'Tyr\'ahnee Phonoi',
  'Alexerine Vesta',
  'Cosiam Talos',
  'Valyria Pan',
  'Mistra Silvanus',
  'Mollyward Calypso',
  'Diokandron Hefaistos',
  'Levenis Oceanus',
  'Circiope Soteira',
  'Octavia Manticora',
  'Azriel Minerva',
  'Lysander Europa',
  'Mareau Loké',
  'Peneldite Karya',
  'Xsander Nike',
  'Cleostasia Medusa',
  'Minerva Proteus',
  'Silvana Venus',
  'Ciodora Athena',
  'Victros Artemis',
  'Willius Atlas',
  'Chester Ares',
  'Margina Metis',
  'Arithena Ceres',
  'Cleoria Minerva',
  'Odanes Satyr',
  'Pandora Demeter',
  'Ikandra Ambrosia',
  'Aurelius Poseidon',
  'Julius Evander',
  'Kartin Landon',
  'Kahina Soteira',
  'Phoenix Venti',
  'Nisio Nerio',
  'Tiberia Silvanus',
  'Dion Fortuna',
  'Irenicia Soteira',
].map((fullName, index) => {
  const nameSplit = fullName.split(' ');
  const family = nameSplit[nameSplit.length - 1];

  return {
    family,
    score: 100 - index * 2,
    type: 'Discipli',
    id: index.toString(),
    year: years[Math.floor(Math.random() * 4)],
    current: true,
    society: societies[Math.floor(Math.random() * 3)],
    rank: index + 1,
    name: nameSplit.slice(0, -1).join(' '),
    status: familyStatus[family] ?? 'b',
  };
});
