name: olympus

services:
  db:
    image: mongo:5.0.25
    restart: always
  frontend:
    user: nextjs
    image: ghcr.io/yxeri/olympus:dev
    command: node server.js
    restart: always
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - DB_HOST=db
      - VIRTUAL_HOST=${NEXT_PUBLIC_INSTANCE_NAME}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - NEXT_PUBLIC_CLOUDINARY_API_KEY=${NEXT_PUBLIC_CLOUDINARY_API_KEY}
      - NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=${NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_ENVIRONMENT=${NEXT_PUBLIC_ENVIRONMENT}
      - NEXT_PUBLIC_INSTANCE_NAME=${NEXT_PUBLIC_INSTANCE_NAME}
    links:
      - db
    ports:
      - "3000:3000"
