name: olympus

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge

  db:
    image: mongo:5.0.25
    restart: always

  frontend:
    depends_on:
      - db
      - nginx-proxy
      - acme-companion
    user: nextjs
    image: ghcr.io/yxeri/olympus:dev
    restart: always
    environment:
      - DB_HOST=db
      - VIRTUAL_HOST=${INSTANCE_NAME}
      - LETSENCRYPT_HOST=${INSTANCE_NAME}
      - VIRTUAL_PORT=3000
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - SECRET=${SECRET}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - INSTANCE_NAME=${INSTANCE_NAME}
      - CALENDAR_START=${CALENDAR_START}
      - CALENDAR_END=${CALENDAR_END}
    links:
      - db
    ports:
      - "3000:3000"

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:
