import { atom } from 'recoil';
import { Person } from '../data';

export const peopleAtom = atom<Person[]>({
  key: 'people',
  default: [
    {
      family: 'Nyx',
      score: 100,
      type: 'Discipli',
      id: 'Cleopensia Nyx',
      year: 1,
      society: 'Bacchus',
      rank: 1,
      name: 'Cleopensia',
      status: 'a'
    },
    {
      family: 'Janus',
      score: 100,
      type: 'Discipli',
      id: 'Themisine Janus',
      year: 1,
      society: 'Bacchus',
      rank: 2,
      name: 'Themisine',
      status: 'a'
    },
    {
      family: 'Deimos',
      score: 100,
      type: 'Discipli',
      id: 'Hercules M. Deimos',
      year: 1,
      society: 'Bacchus',
      rank: 3,
      name: 'Hercules M.',
      status: 'b'
    },
    {
      family: 'Landon',
      score: 100,
      type: 'Discipli',
      id: 'Nezzie Landon',
      year: 1,
      society: 'Bacchus',
      rank: 4,
      name: 'Nezzie',
      status: 'b'
    },
    {
      family: 'Phonoi',
      score: 100,
      type: 'Discipli',
      id: "Tyr'ahnee Phonoi",
      year: 1,
      society: 'Bacchus',
      rank: 5,
      name: "Tyr'ahnee",
      status: 'b'
    },
    {
      family: 'Vesta',
      score: 100,
      type: 'Discipli',
      id: 'Alexerine Vesta',
      year: 1,
      society: 'Bacchus',
      rank: 6,
      name: 'Alexerine',
      status: 'a'
    },
    {
      family: 'Talos',
      score: 100,
      type: 'Discipli',
      id: 'Cosiam Talos',
      year: 1,
      society: 'Bacchus',
      rank: 7,
      name: 'Cosiam',
      status: 'b'
    },
    {
      family: 'Pan',
      score: 100,
      type: 'Discipli',
      id: 'Valyria Pan',
      year: 1,
      society: 'Bacchus',
      rank: 8,
      name: 'Valyria',
      status: 'a'
    },
    {
      family: 'Silvanus',
      score: 100,
      type: 'Discipli',
      id: 'Mistra Silvanus',
      year: 1,
      society: 'Bacchus',
      rank: 9,
      name: 'Mistra',
      status: 'a'
    },
    {
      family: 'Calypso',
      score: 100,
      type: 'Discipli',
      id: 'Mollyward Calypso',
      year: 1,
      society: 'Bacchus',
      rank: 10,
      name: 'Mollyward',
      status: 'a'
    },
    {
      family: 'Hefaistos',
      score: 100,
      type: 'Discipli',
      id: 'Diokandron Hefaistos',
      year: 1,
      society: 'Bacchus',
      rank: 11,
      name: 'Diokandron',
      status: 'a'
    },
    {
      family: 'Oceanus',
      score: 100,
      type: 'Discipli',
      id: 'Levenis Oceanus',
      year: 1,
      society: 'Bacchus',
      rank: 12,
      name: 'Levenis',
      status: 'a'
    },
    {
      family: 'Soteira',
      score: 100,
      type: 'Discipli',
      id: 'Circiope Soteira',
      year: 1,
      society: 'Bacchus',
      rank: 13,
      name: 'Circiope',
      status: 'a'
    },
    {
      family: 'Manticora',
      score: 100,
      type: 'Discipli',
      id: 'Octavia Manticora',
      year: 1,
      society: 'Bacchus',
      rank: 14,
      name: 'Octavia',
      status: 'b'
    },
    {
      family: 'Minerva',
      score: 100,
      type: 'Discipli',
      id: 'Azriel Minerva',
      year: 1,
      society: 'Bacchus',
      rank: 15,
      name: 'Azriel',
      status: 'a'
    },
    {
      family: 'Europa',
      score: 100,
      type: 'Discipli',
      id: 'Lysander Europa',
      year: 1,
      society: 'Bacchus',
      rank: 16,
      name: 'Lysander',
      status: 'b'
    },
    {
      family: 'Loké',
      score: 100,
      type: 'Discipli',
      id: 'Mareau Loké',
      year: 1,
      society: 'Bacchus',
      rank: 17,
      name: 'Mareau',
      status: 'b'
    },
    {
      family: 'Karya',
      score: 100,
      type: 'Discipli',
      id: 'Peneldite Karya',
      year: 1,
      society: 'Bacchus',
      rank: 18,
      name: 'Peneldite',
      status: 'b'
    },
    {
      family: 'Nike',
      score: 100,
      type: 'Discipli',
      id: 'Xsander Nike',
      year: 1,
      society: 'Bacchus',
      rank: 19,
      name: 'Xsander',
      status: 'a'
    },
    {
      family: 'Medusa',
      score: 100,
      type: 'Discipli',
      id: 'Cleostasia Medusa',
      year: 1,
      society: 'Bacchus',
      rank: 20,
      name: 'Cleostasia',
      status: 'b'
    },
    {
      family: 'Proteus',
      score: 100,
      type: 'Discipli',
      id: 'Minerva Proteus',
      year: 1,
      society: 'Bacchus',
      rank: 21,
      name: 'Minerva',
      status: 'a'
    },
    {
      family: 'Venus',
      score: 100,
      type: 'Discipli',
      id: 'Silvana Venus',
      year: 1,
      society: 'Bacchus',
      rank: 22,
      name: 'Silvana',
      status: 'b'
    },
    {
      family: 'Athena',
      score: 100,
      type: 'Discipli',
      id: 'Ciodora Athena',
      year: 1,
      society: 'Bacchus',
      rank: 23,
      name: 'Ciodora',
      status: 'a'
    },
    {
      family: 'Artemis',
      score: 100,
      type: 'Discipli',
      id: 'Victros Artemis',
      year: 1,
      society: 'Bacchus',
      rank: 24,
      name: 'Victros',
      status: 'a'
    },
    {
      family: 'Atlas',
      score: 100,
      type: 'Discipli',
      id: 'Willius Atlas',
      year: 1,
      society: 'Bacchus',
      rank: 25,
      name: 'Willius',
      status: 'a'
    },
    {
      family: 'Ares',
      score: 100,
      type: 'Discipli',
      id: 'Chester Ares',
      year: 1,
      society: 'Bacchus',
      rank: 26,
      name: 'Chester',
      status: 'a'
    },
    {
      family: 'Metis',
      score: 100,
      type: 'Discipli',
      id: 'Margina Metis',
      year: 1,
      society: 'Bacchus',
      rank: 27,
      name: 'Margina',
      status: 'b'
    },
    {
      family: 'Ceres',
      score: 100,
      type: 'Discipli',
      id: 'Arithena Ceres',
      year: 1,
      society: 'Bacchus',
      rank: 28,
      name: 'Arithena',
      status: 'b'
    },
    {
      family: 'Minerva',
      score: 100,
      type: 'Discipli',
      id: 'Cleoria Minerva',
      year: 1,
      society: 'Bacchus',
      rank: 29,
      name: 'Cleoria',
      status: 'a'
    },
    {
      family: 'Satyr',
      score: 100,
      type: 'Discipli',
      id: 'Odanes Satyr',
      year: 1,
      society: 'Bacchus',
      rank: 30,
      name: 'Odanes',
      status: 'b'
    },
    {
      family: 'Demeter',
      score: 100,
      type: 'Discipli',
      id: 'Pandora Demeter',
      year: 1,
      society: 'Bacchus',
      rank: 31,
      name: 'Pandora',
      status: 'a'
    },
    {
      family: 'Ambrosia',
      score: 100,
      type: 'Discipli',
      id: 'Ikandra Ambrosia',
      year: 1,
      society: 'Bacchus',
      rank: 32,
      name: 'Ikandra',
      status: 'b'
    },
    {
      family: 'Poseidon',
      score: 100,
      type: 'Discipli',
      id: 'Aurelius Poseidon',
      year: 1,
      society: 'Bacchus',
      rank: 33,
      name: 'Aurelius',
      status: 'a'
    },
    {
      family: 'Evander',
      score: 100,
      type: 'Discipli',
      id: 'Julius Evander',
      year: 1,
      society: 'Bacchus',
      rank: 34,
      name: 'Julius',
      status: 'b'
    },
    {
      family: 'Landon',
      score: 100,
      type: 'Discipli',
      id: 'Kartin Landon',
      year: 1,
      society: 'Bacchus',
      rank: 35,
      name: 'Kartin',
      status: 'b'
    },
    {
      family: 'Soteira',
      score: 100,
      type: 'Discipli',
      id: 'Kahina Soteira',
      year: 1,
      society: 'Bacchus',
      rank: 36,
      name: 'Kahina',
      status: 'a'
    },
    {
      family: 'Venti',
      score: 100,
      type: 'Discipli',
      id: 'Phoenix Venti',
      year: 1,
      society: 'Bacchus',
      rank: 37,
      name: 'Phoenix',
      status: 'b'
    },
    {
      family: 'Nerio',
      score: 100,
      type: 'Discipli',
      id: 'Nisio Nerio',
      year: 1,
      society: 'Bacchus',
      rank: 38,
      name: 'Nisio',
      status: 'a'
    },
    {
      family: 'Silvanus',
      score: 100,
      type: 'Discipli',
      id: 'Tiberia Silvanus',
      year: 1,
      society: 'Bacchus',
      rank: 39,
      name: 'Tiberia',
      status: 'a'
    },
    {
      family: 'Fortuna',
      score: 100,
      type: 'Discipli',
      id: 'Dion Fortuna',
      year: 1,
      society: 'Bacchus',
      rank: 40,
      name: 'Dion',
      status: 'a'
    }
  ],
});
