import Head from 'next/head';
import PersonList from '../components/PersonList/PersonList';
import Filter from '../components/Filter/Filter';
import Nav from '../components/Nav/Nav';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Nav />
        <div className="main-container">
          <Filter />
          <PersonList />
        </div>
      </main>
    </>
  );
}
