name: Olympus dev
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Test the app
        uses: borales/actions-yarn@v4
        with:
          cmd: test

      - name: Start app
        uses: borales/actions-yarn@v4
        with:
          cmd: start
