name: Olympus dev
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: self-hosted
    environment: preview

    steps:
      - uses: actions/checkout@v4

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install yarn
        run: npm install -g yarn

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
          envkey_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          envkey_NEXT_PUBLIC_CLOUDINARY_API_KEY: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_API_KEY }}
          envkey_NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: ${{ secrets.NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME }}
          envkey_NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          envkey_NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          envkey_SECRET: ${{ secrets.SECRET }}
          envkey_SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          envkey_NEXT_PUBLIC_ENVIRONMENT: ${{ vars.NEXT_PUBLIC_ENVIRONMENT }}
          envkey_NEXT_PUBLIC_INSTANCE_NAME: ${{ vars.NEXT_PUBLIC_INSTANCE_NAME }}

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn build
